### ISSUE TITLE
 Unknown validator: 'UniquenessValidator'

### ISSUE THREAD

**Issue by quolpr** [trailblazer/reform-rails#3]
I cloned your project, then I installed gems:
```
bundle install
```
And after running command:
```
bundle exec rake test
```
I got error:
```
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:

  * development - set it to false
  * test - set it to false (unless you use a tool that preloads your test environment)
  * production - set it to true

/home/quolpr/.rvm/gems/ruby-2.3.1/gems/activemodel-4.2.6/lib/active_model/validations/validates.rb:120:in `rescue in block in validates': Unknown validator: 'UniquenessValidator' (ArgumentError)
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/activemodel-4.2.6/lib/active_model/validations/validates.rb:117:in `block in validates'
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/activemodel-4.2.6/lib/active_model/validations/validates.rb:113:in `each'
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/activemodel-4.2.6/lib/active_model/validations/validates.rb:113:in `validates'
	from /home/quolpr/projects/github/reform-rails/test/uniqueness_validator_test.rb:5:in `<class:FormWithLeakyUniquenessValidation>'
	from /home/quolpr/projects/github/reform-rails/test/uniqueness_validator_test.rb:3:in `<top (required)>'
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `select'
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test:lib" -I"/home/quolpr/.rvm/gems/ruby-2.3.1/gems/rake-10.5.0/lib" "/home/quolpr/.rvm/gems/ruby-2.3.1/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/reform/rails_test.rb" "test/uniqueness_validator_test.rb" ]
/home/quolpr/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/quolpr/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by quolpr** [comment]
This issue looks like this - apotonick/reform#286
I changed model validation from:
```
validates :email, uniqueness: true
```
To:
```
validates :email, unique: true
```
But I am still getting error:
```
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:

  * development - set it to false
  * test - set it to false (unless you use a tool that preloads your test environment)
  * production - set it to true

/home/quolpr/.rvm/gems/ruby-2.3.1/gems/activemodel-4.2.6/lib/active_model/validations/validates.rb:120:in `rescue in block in validates': Unknown validator: 'UniqueValidator' (ArgumentError)
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/activemodel-4.2.6/lib/active_model/validations/validates.rb:117:in `block in validates'
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/activemodel-4.2.6/lib/active_model/validations/validates.rb:113:in `each'
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/activemodel-4.2.6/lib/active_model/validations/validates.rb:113:in `validates'
	from /home/quolpr/projects/github/reform-rails/test/uniqueness_validator_test.rb:5:in `<class:FormWithLeakyUniquenessValidation>'
	from /home/quolpr/projects/github/reform-rails/test/uniqueness_validator_test.rb:3:in `<top (required)>'
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `select'
	from /home/quolpr/.rvm/gems/ruby-2.3.1/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test:lib" -I"/home/quolpr/.rvm/gems/ruby-2.3.1/gems/rake-10.5.0/lib" "/home/quolpr/.rvm/gems/ruby-2.3.1/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/reform/rails_test.rb" "test/uniqueness_validator_test.rb" ]
/home/quolpr/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/quolpr/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by quolpr** [comment]
Oh, I just noticed that tests are broken :smile: 
So, should I write tests for form generators?

**Comment by apotonick** [comment]
Regarding uniqueness: http://trailblazer.to/gems/reform/validation.html#uniqueness-validation :grimacing:

**Comment by fran-worley** [comment]
@quolpr these issues should all be resolved on master as I've just done a load of work sorting the test suite and all tests are now passing.
