### ISSUE TITLE
undefined method `persisted?' (and `to_key`) for #<Hash> when using Composition and `form_for`

### ISSUE THREAD

**Issue by TylerRick** [trailblazer/reform-rails#63]
Without `Composition`, `persisted?` works fine, but with `Composition` it gives this error apparently because it delegates to its `model` which is a Hash of multiple models.

## Steps to reproduce
```
class MyForm < Reform::Form
  include Composition
  model :a

  property :prop_1, on: :a
  property :prop_2, on: :b
end

form = MyForm.new(a: OpenStruct.new, b: OpenStruct.new)
form.persisted?  # undefined method `persisted?' for {:a=>#<OpenStruct>, :b=>#<OpenStruct>}:Hash
```

Using it in a form with `form_for @form` also generates the error, since `form_for` calls `persisted?`.

## Workaround

An easy workaround is to simply add this to form class:
```
  def persisted?
    false
  end
```

**Comment by TylerRick** [comment]
Also ran into this error:
```
undefined method `to_key' for #<Hash:0x00560344c3a328>
actionview (4.2.10) lib/action_view/record_identifier.rb:80:in `record_key_for_dom_id'
actionview (4.2.10) lib/action_view/record_identifier.rb:62:in `dom_id'
actionview (4.2.10) lib/action_view/helpers/form_helper.rb:459:in `apply_form_for_options!'
actionview (4.2.10) lib/action_view/helpers/form_helper.rb:434:in `form_for'
```
Workaround was:
```
  def to_key
    nil
  end
```

**Comment by TylerRick** [comment]
Well, it looks like you can work around it by copying and pasting code!

```
  [:persisted?, :to_key, :to_param].each do |method|
    define_method method do
      model[:main_model].send(method)
    end
  end
```

**Comment by fernandes** [comment]
@TylerRick are you using `reform-rails` gem or just reform?

Usually `reform-rails` add the `Form::ActiveModes` that makes the form builder happy.

`MyForm.ancestors` includes `Reform::Form::ActiveModel?

look the [source](https://github.com/trailblazer/reform-rails/blob/25d37c2465baed3a4ba7dc7c01734a5308dc1732/lib/reform/form/active_model.rb#L10) that's exactly what you are doing :wink:

**Comment by fernandes** [comment]
more info on the [docs](http://trailblazer.to/gems/reform/rails.html#activemodel-compliance)

**Comment by TylerRick** [comment]
Yes, I'm using `reform-rails`. Yes, it delegates those methods to `model`. The problem is that `model` is a *hash* of models and not a single model, because I'm using `include Composition`.

It needs to delegate the messages to `model[:main_model]` instead ... which it *would* do (see debugger output above) except that `Reform::Form::ActiveModel` overrides the correct "default" behavior and makes it delegate to plain `model` instead. So it seems `reform-rails` (`Reform::Form::ActiveModel`) is actually the source of the problem.

**Comment by fernandes** [comment]
ohhhh yeah @TylerRick , now I see what you are facing

How would you make with "plain" Rails?

Create a model the inherits `Hash` and include `ActiveModel::Model` on this class, is an option?
