### ISSUE TITLE
reform-rails 0.1.7 incompatible with reform 2.3

### ISSUE THREAD

**Issue by jamesbebbington** [trailblazer/reform-rails#81]
Having upgraded `reform` from `2.2.4` to `2.3.1`, I'm getting the following error on app boot:

```
NameError: uninitialized constant Errors::Merge
gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant'
gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:9:in `without_bootsnap_cache'
gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `rescue in load_missing_constant'
gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
gems/reform-rails-0.1.7/lib/reform/form/active_model/validations.rb:113:in `<class:Errors>'
gems/reform-rails-0.1.7/lib/reform/form/active_model/validations.rb:112:in `<module:ActiveModel>'
gems/reform-rails-0.1.7/lib/reform/form/active_model/validations.rb:5:in `<main>'
```

As of reform 2.3, `Reform::Form::Errors` no longer exists, however [`reform-rails` references it here](https://github.com/trailblazer/reform-rails/blob/cad6f547d93c790f50334afad8518e7829220470/lib/reform/form/active_model/validations.rb#L113).

Is it time for `0.2.0` to make it out of `rc`? If not, a `0.1.8` release that pins `reform` to ` 2.2.x` would be welcomed. Thanks.

**Comment by seuros** [comment]
did you try with  these versions ?
```
  gem 'reform', '~> 2.3.1'
  gem 'reform-rails', '~> 0.2.0.rc2'
```
